# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: wnonews
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: wnoapp
service: wno-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      DATABASE_URL: postgresql://WNO_DB:WnoDb2024@wno-db.ctyuquysmdcv.us-east-1.rds.amazonaws.com:5432/WNO-DB
          # path: hello
          # method: get
